# データの加工 {#handling}

## サンプルの限定

### 条件に合う行のみ抽出：filter()

## 変数の作成

### 新たな変数を作成：mutate()

### 条件の指定：if_else()

### 複数条件の指定：case_when()

### カテゴリ変数へ変換：factor()

### 必要な列のみ抽出：select()

## 変数の操作化についてのtips

### カテゴリをまとめる

たとえば、親の職業（階級）によって、対象者の学歴がどの程度異なるのかを知りたいとする。このとき、学歴を「中学」「高校」「短大高専」「大学大学院」という4つのカテゴリで定義しているとする。この場合には、たとえば「大学大学院」を1、それ以外を0とすることで、大学以上か大学未満か、という2値のカテゴリにする。

一つひとつのカテゴリに該当する人数が少ないときや、議論を単純化したいときに有効な方法といえる。

### 均等な順序を仮定して連続変数とする

ある程度均等な順序があると仮定できるならば、数値として扱うことを考えてみるとよい。たとえば、性別によって、仕事への満足度が異なるかどうかを知りたいとする。このとき、仕事への満足度は、「全体的にみて、あなたは現在の仕事にどの程度満足していますか」という質問に対して、「非常に満足」「満足」「どちらでもない」「不満」「非常に不満」という5つの選択肢から1つを選択する形式で尋ねられているとする。このときには、「非常に満足」に5、「満足」に4、「どちらでもない」に3、「不満」に2、「非常に不満」に1を振ることで、連続変数に見立てることができる。もちろん、「非常に満足」と「満足」、「満足」と「どちらでもない」の間隔が同じ1であるというのはあくまで仮定であり本当は違うかもしれないということには注意が必要だが、解釈はわかりやすくなるというメリットがある。

| 選択肢         | 調査票上の番号 | 数値化例 |
|----------------|----------------|----------|
| 非常に満足     | 1              | 5        |
| 満足           | 2              | 4        |
| どちらでもない | 3              | 3        |
| 不満           | 4              | 2        |
| 非常に不満     | 5              | 1        |

なお、こうした扱いが認められるかどうかは扱う変数によって異なるので、先行研究での定義を参考にするとよい。たとえば今回のような仕事への満足度についてはおおむねこのような処理は認められているが、「中学」に1、「高校」に2、「短大高専」に3、「大学大学院」に4を振る、というような処理はあまり認められていない。しかしながら、受けた教育年数として、「中学」に9、「高校」に12、「短大高専」に14、「大学」に16、「大学院」に18（など）といった値を振ることはある程度認められている。このあたりは先行研究の操作化を参考にしつつ、最終的には自分たちの関心によって決めるとよいだろう。

### カテゴリ変数の区間の中点をとって連続変数とする

なんらかの区間をとって尋ねられている場合、その区間の中点をとって、連続変数とみなす。たとえば、日本家族社会学会が行っている2008年全国家族調査（NFRJ08）では、「あなたご自身...は、次にあげる...家事を現在どのくらいの頻度で行っていますか」という質問項目で、たとえば「食事の用意」について、以下のような選択肢で家事頻度を尋ねている。

| 選択肢               | 調査票上の番号 | 数値化例 |
|----------------------|----------------|----------|
| ほぼ毎日（週6〜7回） | 1              | 6.5      |
| 1週間に4〜5回        | 2              | 4.5      |
| 1週間に2〜3回        | 3              | 2.5      |
| 1週間に1回くらい     | 4              | 1        |
| ほとんど行わない     | 5              | 0        |

このような場合、週6〜7回という区間の中点をとって6.5、週4〜5回という区間の中点をとって4.5、、etcとすることで、1週間当たりの家事頻度を表す連続変数と見立てることができる。

こうした扱いがどの程度許容されるかについては、先行研究での定義を参照するとよい。

年収などもこうした区間で扱われることがあるが、この場合は中点を定義できない選択肢が設けられていることがある（例：2050万円以上）。こうした場合の扱いについては別途書く（工事中）
