# 社会学のデータ分析でよくある処理 {#domain}

日本の社会学・社会階層研究業界を念頭においたときのデータ分析でよくある処理についてランダムにまとめます。ただし内容は作成者（麦山）の経験と感覚によるもので、業界で標準的な手続きなのかどうかはわかりません。

## SSM職業小分類を大分類にまとめる

いくつかの調査では、調査対象者に仕事の内容を自由記述で尋ね、その回答をもとに、職業名を割り当てているものがある。このときに使われる職業分類が1995年SSM職業小分類と呼ばれるものである。1995年SSM職業章分類は約200の小分類からなり、それぞれの職業に番号が振られている。この番号を振った調査を以下に列挙する。

| 調査名                        | 調査年    | **現職職業小分類** | 初職職業小分類 | **15歳時父親職業小分類** | 15歳時母親職業小分類 |
|-------------------------------|-----------|--------------------|----------------|--------------------------|----------------------|
| 社会階層と社会移動調査（SSM） | 1995      | 有                 | 有             | 有（「主な仕事」）       | 有（「主な仕事」）   |
|                               | 2005      | 有                 | 有             | 有                       | 有                   |
|                               | 2015      | 有                 | 有             | 有                       | 有                   |
| 日本版総合的社会調査（JGSS）  | 2000      | 有                 | 有             | 有                       |                      |
|                               | 2001      | 有                 | 有             | 有                       |                      |
|                               | 2002      | 有                 | 有             | 有                       |                      |
|                               | 2003      | 有                 |                | 有                       |                      |
|                               | 2005      | 有                 | 有             | 有                       |                      |
|                               | 2006      | 有                 | 有             | 有                       |                      |
|                               | 2008      | 有                 | 有             | 有                       |                      |
|                               | 2010      | 有                 | 有             | 有                       |                      |
|                               | 2012      | 有                 | 有             | 有                       |                      |
|                               | 2015      | 有                 | 有             | 有                       |                      |
| 東大社研パネル調査（JLPS）    | 2007-2020 | 有                 | 有             | 有                       | 有                   |

ふつうはこうした200個近い分類をそのまま分析に使うということはなく、少数のカテゴリにまとめて使う。カテゴリへのまとめ方はいくつも種類があるが、ここでは代表的なものとして「SSM職業大分類」と「国勢調査職業分類」の2つを準備する。

## EGP階級分類を作成する

## 旧制学歴と新制学歴の対応

| 旧制学歴                         | 新制学歴                       | 統合学歴（5分類） | 統合学歴（4分類） | 統合学歴（3分類） |
|----------------------------------|--------------------------------|-------------------|-------------------|-------------------|
| 旧制尋常小学校                   | 新制中学校                     | 中学              | 中学              | 初等教育          |
| 旧制高等小学校                   | 新制中学校                     | 中学              | 中学              | 初等教育          |
| 旧制中学校・高等女学校           | 新制高校                       | 高校              | 高校              | 中等教育          |
| 旧制実業学校                     | 新制高校                       | 高校              | 高校              | 中等教育          |
| \-                               | 専修学校高等課程\*             | 高校              | 高校              | 中等教育          |
| \-                               | 専門学校（専修学校専門課程）\* | 専門学校          | 高校              | 高等教育\*\*      |
| 旧制師範学校                     | 新制短大・高専                 | 短大高専          | 短大高専          | 高等教育          |
| 旧制高校・専門学校・高等師範学校 | 新制短大・高専                 | 短大高専          | 短大高専          | 高等教育          |
| 旧制大学                         | 新制大学                       | 大学大学院        | 大学大学院        | 高等教育          |
| 旧制大学                         | 新制大学院                     | 大学大学院        | 大学大学院        | 高等教育          |

\*専修学校高等課程は中学卒業者を対象として職業教育を実施する機関。専修学校専門課程は高校卒業者を対象として職業教育を実施する機関で、ふつう「専門学校」というときにはこちらを指すことが多い。調査票の選択肢に「専門学校」が設けられていた場合も、対象者はおそらくこちらを想定していると思われる。

\*\*国際標準教育分類（ISCED2011）では専門学校はレベル5（Short-cycle tertiary education）とされており、高等教育相当とされている。

## 出身階層（親学歴）の測定

## 年収と労働時間から時間給を作成する
