# さらなる学習のための参考文献 {#reference}

## 実証研究の基礎スキル

社会学（あるいは社会科学）の実証研究論文とはどのようなものか、ということについては、以下の書籍が参考になる。

- 明石芳彦，2018，『社会科学系論文の書き方』ミネルヴァ書房．
- 小熊英二，2022，『基礎からわかる論文の書き方』講談社現代新書．

また、経済セミナーのシリーズは経済学を念頭に置いているもののとてもわかりやすく、参考になる部分も多いのでおすすめ。下に行くほど論文執筆の段階としてより進んだ段階にフォーカスしている。

- 経済セミナー編集部編，2022，『経済セミナー 2022年8・9月号：経済論文の読み方』日本評論社．
- 経済セミナー編集部編，2021，『経済セミナー 2021年8・9月号：経済論文の書き方［はじめの一歩編］』日本評論社．
- 経済セミナー編集部編，2020，『経済セミナー 2020年8・9月号：経済論文の書き方［実証編］』日本評論社．


## Rの使い方

Rは`tidyverse`パッケージの普及以前と以後で望ましいとされる文法が大きく変わっているため、`tidyverse`の使用を前提としたものを使うことを強くおすすめする。また、良書ではあるのだけれど、機械学習など社会学の関心とはやや離れた内容を念頭に置いたものも多く、ぴったりの書籍は少ない。こうしたなかで、日本語で読める書籍としては、以下の書籍がとくにおすすめできる。

-   浅野正彦・矢内勇生，2018，『Rによる計量政治学入門』オーム社．
-   松村優哉・湯谷啓明・紀ノ定保礼・前田和寛，2021，『改訂2版 Rユーザのための RStudio［実践］入門：tidyverseによるモダンな分析フローの世界』技術評論社．

そのほか、ウェブページでRの使い方を紹介してくれている方も多い。以下に挙げたウェブページはいずれも参考になる。

-   [RとRStudioのインストール方法の解説](https://yukiyanai.github.io/jp/resources/)
-   [卒業論文のためのR入門](https://tomoecon.github.io/R_for_graduate_thesis/)
-   [私たちのR：ベストプラクティスの探求](https://www.jaysong.net/RBook/)

## ggplotの解説

本資料では基本的にすべて`ggplot2`を使って図（グラフ）を作成しているが、`ggplot2`による可視化は非常に優れており、さまざまな図を作ることができる。本資料で扱ったものにさらに工夫を重ねれば、より見やすい図を作ることができる。`ggplot2`の使い方に特化した参考文献としては以下のものが挙げられる：

-   Chang, Winston. 2019. *R Graphics Cookbook: Practical Recipes for Visualizing Data. Second Edition.* O'Reilly（石井弓美子・川内崇・瀬戸山雅人訳，『Rグラフィックスクックブック：ggplot2によるグラフ作成のレシピ集』オライリー・ジャパン）．
-   Healy, Kieran. 2019. *Data Visualization: A Practical Introduction.* Princeton University Press.（瓜生真也・江口哲史・三村喬生訳，『データ分析のためのデータ可視化入門』講談社．）[^reference-1]

[^reference-1]: [著者により原著のドラフトが公開](https://socviz.co/)されている。

## 統計学・計量分析を学ぶ

統計ソフトの使い方を学ぶだけではなくて、統計学や計量分析の方法についての理論的な側面も学ぶと、より適切な分析をすることにつながるだろう。

社会学の実証分析でもっともよく分析される社会調査データというのがどのような性質をもち、どのような方法で収集されているのかを知っておくと、その意味をより理解できるようになるだろう。最近だと以下の書籍はよい教科書だと思う。

- 轟亮・杉野勇・平澤和司編，2021，『入門・社会調査法［第4版］：2ステップで基礎から学ぶ』法律文化社．
- 毛塚和宏，2022，『社会科学のための統計学入門：実例からていねいに学ぶ』講談社．

計量分析にはさまざまな方法があるが、そのほとんどで基礎になっているのが回帰分析であり、回帰分析をもっともきちんと説明しているのが計量経済学の教科書である。なので、計量経済学の入門書を読むのがいろいろな計量分析の方法を学ぶ上で有益だろう。

- 田中隆一，2015，『計量経済学の第一歩：実証分析のススメ』有斐閣．
- 山本勲，2015，『実証分析のための計量経済学：正しい手法と結果の読み方』中央経済社．
- 西山慶彦・新谷元嗣・川口大司・奥井亮，2019，『計量経済学』有斐閣．（注：数学をやるぞという覚悟が必要です）

また、最近は研究の世界でもそうでない世界でも因果推論が重要だといわれはじめて久しい。因果推論について勉強することは、仮に因果推論を使わないとしても自分が何を行っているのか、分析する際に何を考える必要があるのかを明確にする上で役に立つ。以下の書籍は内容もそこまで難しくすぎないのでおすすめできる。

- 中室牧子・津川友介，2017，『原因と結果の経済学』ダイヤモンド社．
- 松林哲也，2021，『政治学と因果推論：比較から見える政治と社会』岩波書店．
- 安井翔太・株式会社ホクソエム，2020，『効果検証入門：正しい比較のための因果推論／計量経済学の基礎』技術評論社．
