# 論文のまとめ方 {#writepaper}

期末レポートの分量は、Microsoft Wordの左下の文字数（単語数）表記で**12,000字以上〜20,000字以内**とする。ただし、タイトル・名前・要約部分は文字数に含まない。図表内の文字は文字数に含まないが、1点につき400字と換算して文字数に含める。

以下では、上記の分量の実証研究論文を書くことを念頭においた上での構成や、形式上の注意事項について記す。ここで紹介する形式は絶対というわけではないが、標準的な構成がどのようなものであるのかを押さえておくと、何を考えればよいのか、何を書けばよいのかが明確になるというメリットがある。

## 全体の構成

おおまかにいって、実証研究論文はIMRaD（Introduction, Methods, Results, and Discussion）とよばれる形式をとる。社会学の場合は先行研究や理論を長めに検討するため、IntroductionとMethodの間にLiterature review（先行研究の検討）あるいは、Theoretical framework（理論枠組み）といった節が入り、全部で5節の構成を標準とすることが多い。

よくある構成は次のようなものである。

> タイトル
>
> 要約
>
> 1.  序論
>
> 2.  先行研究（理論枠組み）と仮説
>
> 3.  方法
>
>     1.  データと分析対象
>     2.  変数
>     3.  分析手法
>
> 4.  結果
>
>     1.  記述的分析（クロス表、平均値の比較など）
>     2.  回帰分析など
>
> 5.  結論 
>
> 謝辞
> 
> 参考文献

以下では、一つひとつについてくわしくみていく。

## タイトル

タイトルは、その論文が何の論文であるのかを示す最も重要な箇所となる。そのため、何をやっているのかがひと目でわかるタイトルを付けることが大事である。「期末レポート」はタイトルではない。

たとえば「XがYに与える影響」とか、「X1とX2の間にYの格差が生まれる要因」とか、そういったタイトルがつくことが多い。具体的にどのようなタイトルがついているかは、先行研究を参考にしよう。

## 要約

**400字以内**の要約をつける。要約は論文全体の内容をコンパクトにまとめたもので、要約を読めば論文の概要がわかる、というものになっている必要がある[^writepaper-1]。標準的には、次のように構成することが多い。字数がもっと長い場合には、今後の課題を加えたり、結果についてよりくわしく書く。

[^writepaper-1]: つまり、映画の予告や小説の裏表紙のあらすじみたいに「さわりだけ触れている」ようなものはよくない。

-   問題背景と先行研究の限界（1--2文）
-   目的・問い（1文）
-   方法（1文）
-   結果（2--3文）
-   結論（1文）

## 序論

序論は、次の全3〜6段落で構成する。

### 問題背景（1段落）

研究で扱うトピックが社会問題としてand/or社会学的に重要であることを述べる。

「自分が関心を持った」というのは最初のモチベーションとして大事だが、それ以上に、より広い社会でこれが問題なのだ、ということを述べる。

何らかの（重要な・解決すべき）社会問題があることを提示するのが一般的（教育機会の不平等、男女の賃金格差...etc）。規模感を示すために公的統計の値などを提示するのも良い。

### 先行研究の検討（1--2段落）

先に述べた問題に関連して、先行研究がこれまでに何を明らかにし、何を明らかにしていないのかを提示する。

ここでは、先行研究の内容を一つひとつ詳しく述べるのではなく、調べた先行研究をまとめた全体像を示す。この全体像から、（重要であるにもかかわらず）明らかになっていないことが何であるのかを示す。

### 研究目的（1--2段落）

研究目的（問い）を提示する。「xxxを明らかにする」「どの程度yyyなのか？」など、何をやるのかが明確になるような具体的な目的や問いを提示する。

研究目的のもつ意義などをさらに書くこともある。

### 本文の構成（1段落、任意）

「2節ではxxx。3節ではyyy。...」というふうに、序論以降の各節でどのような内容を扱うのかについて簡潔に述べる。これはあってもなくてもよい。

## 先行研究（理論枠組み）と仮説

通常、節の下に2--3程度の項を設ける。論文によって分け方は様々なので、これと決まった形式はない。しかし、進むにつれて抽象的な議論から具体的な議論に向かっていくのが読みやすいだろう。多くの研究は、

-   （現象を説明する）理論
-   先行研究でわかっている（いない）こと：序論で書いた内容をよりくわしく述べる。
-   仮説とその根拠

というふうな流れを取っている論文が多い。

## 方法

分析に使う変数について説明する。同じ変数でもデータによって異なる定義で作る場合があるので、他の人にも定義がわかるように。

一般的でない分析手法を使う場合には、具体的な説明が必要。説明が必要かどうかは、聞く人の理解度によって異なる。この授業のレポートでは、度数分布、クロス集計、相関係数、平均値の比較、回帰分析くらいであれば、説明は不要。

### データと分析対象

第1段落では、何の調査データを使用するのか、そのデータがいつ、どのような人を対象にして、どのように収集されたのかを書く。また、このデータが研究目的に照らして適切なデータであること（その理由）を書く。

第2段落では、上記調査データのうち誰を分析の対象とするのかを書く（例:25--64歳の有業の男女、ひとり親世帯のみ、etc）。可能であれば、分析対象者の人数について書く。

### 変数

分析に使用する変数について書く。

第1段落では、従属変数について書く。変数の説明については、たとえばたんに「最終学歴」とだけ書くのではなく、どのようなカテゴリに分けたのかといったことまで書く。いくつかの変数を組み合わせて加工する場合（例：年収と労働時間を組み合わせて時間あたり賃金の変数を作成した場合）には、その手続きについても書く。一般的でない変数については、どのような質問項目でそれを尋ねているのかということについても書く。

第2段落では、独立変数について書く。とくに、最も主眼となる変数を一番はじめに書く。男女で賃金がどの程度異なるのかを分析するという場合であれば性別、ひとり親世帯出身者とふたり親世帯出身者で教育達成がどの程度異なるのかを分析するという場合であれば世帯構成（ひとり親か、ふたり親か）が、ここに書くべき変数ということになる。

第3段落では、媒介変数や交互作用の検討に使う変数について書く。男女の賃金格差が職業の違いによってどの程度説明できるのかを分析するという論文であれば、職業に関する説明がここに書くべき内容になる。

最後に、その他の統制変数について書く。ない場合は書かなくてもよい。第2段落や第3段落が極端に短いようであれば、合わせてもよい。

### 分析手法（任意）

一般的でない分析手法を使う場合には、具体的な説明が必要。説明が必要かどうかは、聞く人の理解度によって異なる。この授業では、度数分布、クロス集計、相関係数、平均値の比較、回帰分析くらいであれば、説明は不要。それ以外の手法を使う場合には、説明を書く。

## 結果

結果では、どのような分析をしたのか、その結果について記述する。

表や図を使う場合、細かい数字を一つひとつ確認する必要はない。しかし、仮に読者が表や図を見なかったり、あるいはそれを読むことができる知識を持っていなかったとしても、どのような結果なのか本文を読めば理解できるような記述が望ましい。「もしこの授業を取っていない（=統計や社会学を勉強していない）大学の友だちがこのレポートを読んだとしたら、理解できるだろうか？」というのが一つの目安になるだろう。

原則として「結果」の部分では過度に考察に踏み込むことはせず、結果が表すことの意味については「結論」の部分で論じる。

### 記述的分析

### 回帰分析

## 結論

### 背景と目的の再確認（1段落）

1.  研究の（社会的な）背景を再確認する。
2.  先行研究でわかっていなかったことを再確認する。
3.  研究目的あるいは問いを再確認する。

読者は論文をさかのぼって読まない。なので、改めて「序論」で示した内容を確認し、ここで掲げた問いに対する答えを提示するための準備をする。

### 分析結果の要約と解釈（2--3段落）

分析の結果を要約する。そのうえで、その結果がどのようなことを意味しているのか、考察や議論を展開する。

「先行研究・仮説」の節で事前の予測（仮説）を立てたのだとしたら、それが当てはまったか、当てはまらなかったかについて書く。当てはまったとしたら、その仮説を導いたときの根拠に照らしながら、考察や議論を述べる。当てはまらなかったとしたら、なぜ当てはまらなかったのか、その原因について考察する。

### 含意・示唆（1--2段落）

分析結果を受けて、さらに広い議論を展開する。たとえば、次のようなものが挙げられる。

-   政策的含意：本研究の分析結果を踏まえれば、論文冒頭で掲げた社会問題を解決するためには、このような政策が有効なのではないか？従来は見落とされてきた、このような層への支援が必要なのではないか？
-   学術的含意：先行研究は主としてこのような点に焦点を当ててきたが、それでは不十分なのではないか？先行研究が提示してきた説明というのは、必ずしも正しくないのではないか？

もちろん、研究目的から大きく外れた議論を展開してはいけない。あくまで、分析結果（や先行研究）をもとにした自分なりの含意を述べる。

### 課題・限界（1段落）

本論文に残る課題、限界について書く。ただし、反省文ではなく、今後の研究では、このようなことを分析すると良いのではないかというような方向性を提示する。そうすると、この論文を読んだ他の人が研究を進めやすくなる。

課題や限界は、あまり長く書き過ぎないように[^writepaper-2]。できなかったことよりもできたことに目を向けよう。

[^writepaper-2]: 大学院時代、指導教員に「論文の最後に課題を長々と書くな」と言われたのが懐かしい。結論での議論や考察に比べて課題が極端に長いと、せっかく行った研究のアピールポイントが削がれてしまうようにも感じる。ただし、これについては課題をしっかり書くのが科学的に誠実な態度だと言う人もいて、好みがあると思う。

### まとめ（1段落、任意）

最後が課題で終わるとなんだか後ろ向きの印象を残してしまう。そこで最後に、「こうした課題はあるけれど、でも本論文はとても重要な貢献をしたんだよ！」ということを書く。

## 謝辞

社会調査データは回答者、調査の企画・実施者を含めたくさんの人の協力があってはじめて成り立っていることを忘れてはいけない。既存社会調査データを借り出して論文を書いた場合には、**必ず**データを利用した旨の謝辞を書くようにする。

JGSSの場合は、[こちらのページ](https://jgss.daishodai.ac.jp/data/dat_acknowledgement.html)を参照して謝辞を書く。たとえばJGSS2015を利用した場合には次のような謝辞を書くことになっている：

> 日本版General Social Surveys（JGSS）は、大阪商業大学JGSS研究センター（文部科学大臣認定日本版総合的社会調査共同研究拠点）が、大阪商業大学の支援を得て実施している研究プロジェクトである。JGSS-2015は、JSPS科研費JP26245060、JP15H03485、JP24243057、大阪商業大学アミューズメント産業研究所、日本経済研究センター研究奨励金2014年度（岩井紀子）、労働問題に関する調査研究助成金2015年度（岩井八郎ほか）の支援を受けた。

SSJDA経由でデータを取得した場合は、次のように書く（「2005年SSM日本調査，2005」の例）：

> 二次分析にあたり、東京大学社会科学研究所附属社会調査・データアーカイブ研究センターSSJデータアーカイブから「2005年SSM日本調査，2005」（2015SSM調査管理委員会）の個票データの提供を受けた。

謝辞の記載方法については、データ利用の際の規約などをよく確認すること。

## 参考文献

本文中で引用した参考文献を記載する。参考文献は著者名のアルファベット順に並べる。引用していないものは書かない。形式については以下を参照のこと。

## 形式上の注意事項

形式上の注意事項は以下のとおり。Wordのテンプレートファイルは[こちら（準備中）]()にアップロードしている。

### 推奨するWordの設定

タイトルのフォントサイズは16pt, サブタイトルは14pt, 章タイトルは12pt, 節タイトルは11pt, その他本文は10.5ptを目安とする。

章タイトルや節タイトルのフォントはゴシック体（游ゴシック、ヒラギノ角ゴシックなど）、それ以外は明朝体（游明朝、ヒラギノ明朝など）とする。

本文中のアルファベットや半角数字、表中のフォントはTimes New Romanを推奨する。

余白は上下左右いずれも30mmとし、1行あたりの文字数は40、1ページあたりの行数は35とする。

フッターにはページ数を記載する。ページ数の位置は中央揃えとする。

### 引用の形式

原則としてauthor-date方式とする。つまり、脚注で引用文献などを示すのではなく、該当する記述の後に（筆者 出版年）を付け、末尾に参考文献としてその書誌情報を記載する方式。何らかの書籍、論文、新聞、雑誌、ウェブサイト、等々、何らかの先行研究や資料を引用するときには必ず引用を記載し、自分の主張や記述とは区別する。より細かい記載方法については[「社会学評論スタイルガイド」](https://jss-sociology.org/bulletin/guide/quotation/)におおむね準拠する。

本文中の記載例：

-   近年では男性と女性ともに非正規雇用者は正規雇用者と比べて結婚しにくいことが示されている（佐々木 2012; 麦山 2017）。

-   Blau and Duncan (1967)が提示した地位達成モデルでは...

### 図表の形式

原則として、表と図はそれぞれ別々の通し番号をつける。

表や図には一見してわかりやすいタイトルをつける。表や図の下には、必要に応じて出所や注をつける。

カテゴリや軸はたんにRの変数名ではなく、それが何を表しているかがわかるような名前がついている状態にする。たとえば1, 2, というふうな数値であれば「そう思う」「どちらかといえばそう思う」...などといった値が入っているほうが良いし、クロス表であれば、行と列がそれぞれ何の変数であるのかわかるようにする、といったような具合である。

表は以下のようにWord上の表機能を使ってきれいな状態にすることが好まれることが多い。表を作成する場合、罫線はできるだけ少なくし、かつ、横の罫線のみ使うというのが一般的。なおこの授業では、Rのgtsummary::tbl_summary()やgtsummary::tbl_cross()、modelsummary::msummary()を使ってある程度きれいな状態にできるのであれば、その出力結果を貼り付けてもよい。

図であれば、文字が小さすぎないようにする。

図表の例は[先に示したテンプレート（準備中）]()上に記載している。

### 脚注

本文の流れのうえでは不要であるが、より詳細な情報などを記載したいときには脚注を使用する[^writepaper-3]。Wordの脚注機能を使ってつける。

[^writepaper-3]: たとえばこんなふうに。

### 参考文献の記載例

社会学評論スタイルではサブタイトルは------（2倍ダッシュ）で表記しているが、この授業では、：（コロン）で構わない。[『理論と方法』スタイル](http://www.jams-sociology.org/?page_id=50)。

また英語論文のスタイルは、社会学評論スタイルではなく、[American Sociological Associationスタイル](https://www.asanet.org/sites/default/files/savvy/documents/teaching/pdfs/Quick_Tips_for_ASA_Style.pdf)にしている。これはたんに自分の好みの問題なので、統一的な形式が取られていれば別のものでも構わない。

#### 書籍の場合

岩間暁子，2008，『女性の就業と家族のゆくえ：格差社会のなかの変容』東京大学出版会．

浅野正彦・矢内勇生，2018，『Rによる計量政治学』オーム社．

#### 編著書籍中の論文の場合

松浦司，2021，「有配偶者の出産意欲の日台比較」寺村絵理子編『日本・台湾の高学歴女性』晃洋書房，54--72．

#### 雑誌論文の場合

余田翔平，2012，「子ども期の家族構造と教育達成格差」『家族社会学研究』24(1): 60--71．

永吉希久子，2012，「日本人の排外意識に対する分断労働市場の影響：JGSS-2006の分析から」『社会学評論』19--35．

#### 英語論文の場合

Torche, Florencia. 2011. "Is a College Degree Still the Great Equalizer? Intergenerational Mobility across Levels of Schooling in the United States." *American Journal of Sociology* 117(3):763--807.

#### 英語の書籍の場合

Blau, Peter M. and Otis Dudley Duncan. 1967. *The American Occupational Structure*. Free Press.

#### 翻訳書の場合

Watts, Duncan J. 2011. *Everything is Obvious \*Once You Know the Answer: Why Common Sense is Nonsense.* Atlantic Books.（青木創訳，2014，『偶然の科学』早川書房．）

#### ウェブサイトの場合

内閣府，2021，「令和3年版 男女共同参画白書」内閣府男女共同参画局ホームページ．（2021年11月22日閲覧，<https://www.gender.go.jp/about_danjo/whitepaper/r03/zentai/index.html>）
