# さらなる学習のための参考文献 {#reference}

学部レベルを念頭において、学習のために役立つだろう参考文献をリストする。

## 実証研究の基礎スキル

社会学（あるいは社会科学）の実証研究論文とはどのようなものか、ということについては、以下の書籍が参考になる。

- 明石芳彦，2018，『社会科学系論文の書き方』ミネルヴァ書房．
- 小熊英二，2022，『基礎からわかる論文の書き方』講談社現代新書．
- 経済セミナー編集部編，2022，『経済論文の書き方』日本評論社．

## Rの使い方

Rは`tidyverse`パッケージの普及以前と以後で望ましいとされる文法が大きく変わっているため、`tidyverse`の使用を前提としたものを使うことを強くおすすめする。また、良書ではあるのだけれど、機械学習など社会学の関心とはやや離れた内容を念頭に置いたものも多く、ぴったりの書籍は少ない。こうしたなかで、日本語で読める書籍としては、以下の書籍がおすすめできる。

-   藤井亮輔，2021，『超入門！Rでできるビジュアル統計学：学会・論文発表に役立つデータ可視化マニュアル』金芳堂．
-   浅野正彦・矢内勇生，2018，『Rによる計量政治学入門』オーム社．

そのほか、ウェブページでRの使い方を紹介してくれている方も多い。以下に挙げたウェブページはいずれも参考になる。

-   [RとRStudioのインストール方法の解説](https://yukiyanai.github.io/jp/resources/)
-   [卒業論文のためのR入門](https://tomoecon.github.io/R_for_graduate_thesis/)
-   [私たちのR：ベストプラクティスの探求](https://www.jaysong.net/RBook/)

## ggplotの解説

本資料では基本的にすべて`ggplot2`を使って図（グラフ）を作成しているが、`ggplot2`による可視化は非常に優れており、さまざまな図を作ることができる。本資料で扱ったものにさらに工夫を重ねれば、より見やすい図を作ることができる。`ggplot2`の使い方に特化した参考文献としては以下のものが挙げられる（下に行くほどむずかしい）：

-   藤井亮輔，2021，『超入門！Rでできるビジュアル統計学：学会・論文発表に役立つデータ可視化マニュアル』金芳堂．
-   Chang, Winston. 2019. *R Graphics Cookbook: Practical Recipes for Visualizing Data. Second Edition.* O'Reilly（石井弓美子・川内崇・瀬戸山雅人訳，『Rグラフィックスクックブック：ggplot2によるグラフ作成のレシピ集』オライリー・ジャパン）．
-   Healy, Kieran. 2019. *Data Visualization: A Practical Introduction.* Princeton University Press.（瓜生真也・江口哲史・三村喬生訳，『データ分析のためのデータ可視化入門』講談社．）（[著者により原著のドラフトが公開](https://socviz.co/)されている）

## 統計学・計量分析を学ぶ

統計ソフトの使い方を学ぶだけではなくて、統計学や計量分析の方法についての理論的な側面も学ぶと、より適切な分析をすることにつながるだろう。データ分析とはいったい何をするのかということについての入門書としては、（英語だが）以下の本が最もよく書かれている。

- Llaudet, Elena and Kosuke Imai. 2022. *Data Analysis for Social Science: A Friendly and Practical Introduction.* Princeton University Press.

社会学の実証分析でもっともよく分析される社会調査データというのがどのような性質をもち、どのような方法で収集されているのかを知っておくと、その意味をより理解できるようになるだろう。最近だと以下の書籍はよい教科書だと思う。

-   轟亮・杉野勇・平澤和司編，2021，『入門・社会調査法［第4版］：2ステップで基礎から学ぶ』法律文化社．
-   毛塚和宏，2022，『社会科学のための統計学入門：実例からていねいに学ぶ』講談社．

計量分析にはさまざまな方法があるが、そのほとんどで基礎になっているのが回帰分析であり、回帰分析をもっともきちんと説明しているのが計量経済学の教科書である。なので、計量経済学の入門書を読むのがいろいろな計量分析の方法を学ぶ上で有益だろう。

-   田中隆一，2015，『計量経済学の第一歩：実証分析のススメ』有斐閣．
-   西山慶彦・新谷元嗣・川口大司・奥井亮，2019，『計量経済学』有斐閣．（注：すばらしい教科書ですが、数学をやるぞという覚悟が必要です）
-   Wooldridge, Jeffrey M. 2019. Introductory Econometrics: A Modern Approach, 7th Edition. Cengage Learning.（注：すばらしい教科書ですが、数学をやるぞという覚悟が必要です）

また、最近は研究の世界でもそうでない世界でも因果推論が重要だといわれはじめて久しい。因果推論について勉強することは、仮に因果推論を使わないとしても自分が何を行っているのか、分析する際に何を考える必要があるのかを明確にする上で役に立つ。以下の書籍は内容もそこまで難しすぎないのでおすすめできる（下に行くほどむずかしい）。

-   中室牧子・津川友介，2017，『原因と結果の経済学』ダイヤモンド社．
-   松林哲也，2021，『政治学と因果推論：比較から見える政治と社会』岩波書店．
-   安井翔太・株式会社ホクソエム，2020，『効果検証入門：正しい比較のための因果推論／計量経済学の基礎』技術評論社．
