# 研究発表をする {#presentation}

データ分析をしたり、論文を書いている途中の段階で、現時点での研究成果や進捗状況について研究発表をすることがある。報告の際には、スライド（PowerPointなど）を使って報告する。

スライドを作る際には、次のような形式を参考にするとよい。

## タイトルと名前

1ページには論文のタイトルと発表者の名前を記載する。「研究発表」というタイトルをつけてはいけない。

## 序論・問題背景

### 問題背景（1ページ）

これから扱うテーマがなぜ重要なのかを説明する。

### 先行研究で明らかになっていない点（1ページ）

先行研究で何が明らかになっていて、何が明らかになっていないのかを提示する。

### 研究目的・問い（1ページ）

研究目的ないし問いについて述べる。

問いは、実際に検証する具体的で絞られた問いである必要がある。

### 仮説（任意, 1ページ）

問いに関連して仮説を立てた場合には、その仮説、および仮説を導くために用いた理論について説明する。

## 方法

### データと分析対象（1ページ）

**データ**：どのようなデータを使用したのか、その調査データの名前、どのような人や組織などを対象とした調査なのか、いつ実施された調査なのかを記載する。

**分析対象**：上記の調査データから一部の対象者を選択した場合には、どのような対象者を選択したのかを説明する。

### 用いる変数（1ページ）

従属変数とする変数、独立変数とする変数、統制変数とする変数について、それぞれ説明する。

### 分析方法（任意, 1ページ）

特殊な分析方法を使う場合に限り、説明する。このウェブページに載っているような方法を使っている場合には、解説の必要はない。

## 分析結果

分析した結果を提示する。ただし、やったことを何でもかんでも提示するのではなく、最初に立てた問いに関係するものを主として取り上げるのが原則。

### 2変数の分析（xページ）

クロス集計表、平均値の比較などといった2変数単位の分析を中心にする。

### 回帰分析など（xページ）

他の要因を統制したうえでも関連が見られるかどうか、他の変数と組み合わせた場合の結果などについて、回帰分析を行った際の結果を提示する。

## 結論

### 分析結果のまとめ（1ページ、任意）

得られた分析結果を要約する。10分程度の短い報告の場合には不要。

### 考察・課題（1ページ）

得られた分析結果の考察や、仮説が支持された（されなかった）としたらそれはなぜかを記載する。

また、研究内容に関して現在悩んでいる点を記載する。

## その他の一般的なTips

### 文字は大きく少なく

左上から右下まで文字が詰まったスライドはとても見にくい。可能な限り文字を少なめに、かつ大きくできるとよい。

### スライドにはページ数を書く

質疑応答の際に、スライドのページ数に言及することがある。その際にページ数があると便利なので、つけておくとよい。

### スライドつくりの参考資料

[麦山のResearchmap](https://researchmap.jp/mugiyama)にスライドをアップロードしているので、みてみると参考になるかもしれない。

ただし、報告時間が15分程度ある場合を念頭に置いており、先行研究や背景についての説明がもう少し多くなっていることに注意すること。

ほかにも、みやすいスライドの作り方を解説した資料はたくさんある。たとえば以下のような書籍や資料を参考にするとよい。

- [伝わるデザイン：研究発表のユニバーサルデザイン](https://tsutawarudesign.com/)：たいへんよくまとまっているウェブサイト。筆者らのアイデアをまとめて、さらに詳しく解説したものとして以下の書籍がある。

- 高橋佑磨・片山なつ，2021，『伝わるデザインの基本 増補改訂3版 良い資料を作るためのレイアウトのルール』 技術評論社．

また、よりやさしく説明した資料として以下がある。「高校生の」とあるが、大学生はもちろん、研究者にとっても大変有益。

- [伝わるデザイン：高校生のための研究発表の手引き](https://student.tsutawarudesign.com/slide_design/)

