# 論文のまとめ方 {#writepaper}

本章では、データ分析の結果をもとに論文をまとめる際の構成や注意事項を説明する。

もちろん、ここで紹介する形式は絶対というわけではなく、標準的な構成の一例に過ぎない。しかし、標準的な構成がどのようなものであるのかを押さえておくと、論文を書く上で何を考えればよいのか、いったい何をどのように書けばよいのか、といったことが明確になるというメリットがある。

なお、期末レポートの分量は、Microsoft Wordの左下の文字数（単語数）表記で**12,000字以上〜20,000字以内**とする（タイトル・名前・要約・参考文献・脚注などすべて含む）。図表内の文字は文字数に含まないが、図表1点につき400字と換算して文字数に含める。

## 全体の構成 {#writepaper_structure}

おおまかにいって、実証研究論文はIMRaD（Introduction, Methods, Results, and Discussion）とよばれる形式をとる。社会学の場合は先行研究や理論を長めに検討するため、IntroductionとMethodの間にLiterature review（先行研究の検討）あるいは、Theoretical framework（理論枠組み）といった章が入り、全部で5章程度の構成を標準とすることが多い。

よくある構成は次のようなものである。

> タイトル
>
> 要約
>
> 1.  序論
>
> 2.  先行研究・理論枠組み・仮説
>
> 3.  方法
>
>     1.  データと分析対象
>     2.  変数
>     3.  分析手法
>
> 4.  結果
>
>     1.  記述的分析（クロス表、平均値の比較など）
>     2.  回帰分析など
>
> 5.  結論
>
> 謝辞
>
> 参考文献

なお、論文の構成を学ぶためには、たくさんの（それなりに質の高い）論文を読んで構成を体得するのが最も近道である。あるいは、標準的な構成にしたがった論文を参考にして、その構成を真似るのもよいだろう[^12-writepaper-1]。

[^12-writepaper-1]: 自分でいうのもおかしいかもしれないが、麦山はいつもこうした標準的な構成に準拠して論文を書いているので、麦山の過去に書いた論文を真似するとだいたい標準的な構成になるだろう。もちろん、文章そのものは盗用しないように。

論文のまとめ方について注記しておく。上記のように論文の標準的な構成を示したが、これは上から順番に書いていくものではまったくない[^12-writepaper-2]。書けるところは先に書いてしまってもよい。また、結果を修正したり結論に変更が生じれば、それに対応して序論や先行研究の部分も変わることは普通である。執筆の過程で、さらに調べるべき先行研究が出てくることもある。何度も行き来しながら、少しずつ全体を完成させていくものである。

[^12-writepaper-2]: 締切間際に書く大学の授業のレポートはまさに上から下へと順番に書いていって見直さないものの典型かもしれないが。。。

データを分析する前にあらかじめ研究計画を立てたものの、分析の過程で、研究計画の中身、たとえば取り上げる先行研究や、問い、あるいは用いる変数についての修正を行ったりしたと思われる。こうしたことは当然起こることなので、はじめに作成した研究計画に固執する必要はなく、適宜取り上げる先行研究などを変更しても構わない。タイトルなども変更して、より研究の中身を的確に表すようなものに変更しても問題ない。

ただし、分析結果を見たあとに、同じデータを用いて、当初立てていなかった仮説をあたかも最初から立てていたかのように偽装して議論を組み立てるのは、厳密に不正行為とは言えないものの、「疑わしい研究行為」（Questionable Research Practice）として懸念されている。「問いを立てる→仮説を立てる（予想する）→実証する」というのが社会科学研究の基本であり、「何か分析して結果を見る→結果をよく見せるように問いを立てる→結果に合うように仮説の方向を修正する」、というのは間違った手順である。

ただし、データの構造やデータ分析に未習熟な場合には、実際には当初の研究計画で立てていた問いが必ずしも明確に定義されていなかったということはよくある（あると思っていた変数がなかった、使えると思っていた変数に問題があった、何を統制すべきかの考慮が不十分であった、など）。このような場合には、問いや仮説を事前に修正したうえで、分析を実施するということになる。

また、事前に問いや仮説を厳格には設定せず、さまざまな分析を行うことを指して、探索的分析（Exploratory analysis）という。探索的分析の典型例としては、データをサブグループ（男性と女性、若年層と壮年層、など）に分割しても同じような結果が見られるかどうかを分析してみる、ということが挙げられる。主要な問いに関する分析を行ったうえで、こうした分析を行うことは、結果がどの程度安定的なのか、どのグループでも同じような関係がみられるのか、を考察するうえで役に立つ。このような場合には、無理やり問いや仮説を立てる必要はなく、すなおに探索的な分析であると述べるとよい。具体的には「方法」の章で、主たる分析に加えて探索的分析を行うことを述べるとよいだろう。

## タイトル {#writepaper_title}

タイトルは、その論文が何の論文であるのかを示す最も重要な箇所となる。そのため、**何をやっているのかがひと目でわかる**タイトルを付けることが大事である。「期末レポート」はタイトルではない。

たとえば「XがYに与える影響」とか、「X1とX2の間にYの格差が生まれる要因」とか、そういったタイトルがつくことが多い。具体的にどのようなタイトルがついているかは、先行研究を参考にしよう。

## 要約 {#writepaper_summary}

**400字以内の要約**をつける。要約は論文全体の内容をコンパクトにまとめたもので、**要約を読めば論文の概要がわかる**、というものになっている必要がある[^12-writepaper-4]。標準的には、次のように構成することが多い。字数がもっと長い場合には、今後の課題を加えたり、結果についてよりくわしく書く。

[^12-writepaper-4]: つまり、映画の予告や小説の裏表紙のあらすじみたいに「さわりだけ触れている」ようなものはよくない。

-   問題背景と先行研究の限界（1--2文）
-   目的・問い（1文）
-   方法（1文）
-   結果（2--3文）
-   結論（1文）

## 序論 {#writepaper_introduction}

**序論は読者の関心を引きつけて自分の問いへと導く章であると同時に、論文全体の見取り図を示す**章である。次の全3〜5段落程度で構成する。ちょうど、[研究計画書について説明した第1章](#plan)のうち、「[研究背景](#plan_background)」「[研究目的・問い](#plan_question)」で言及した内容と意識することは同じである。もちろん、データ分析を経て多かれ少なかれ研究背景や問いを修正したり発展させたり、先行研究のリサーチを進めて再検討した部分もあるだろうから、研究計画書とまったく同じに書く必要はない。

### 問題背景（1段落）

研究で扱うトピックが社会問題としてand/or社会学的に重要であることを述べる。

もちろん、「自分が関心を持った」というのは最初のモチベーションとして大事だが、「自分が関心をもった」というだけでは、他の人にとっては説得的できない。他の人にとって関心をもってもらえるような理由を述べることが大事である。

### 先行研究の検討（1--2段落）

先に述べた問題に関連して、先行研究がこれまでに何を明らかにし、何を明らかにしていないのか、あるいは先行研究に存在する限界点を提示する。

ここでは、先行研究の内容を一つひとつ詳しく述べるのではなく、調べた先行研究をまとめた全体像を示す。この全体像から、（重要であるにもかかわらず）明らかになっていないこと・解決されていない課題が何であるのかを示す。

### 研究目的（問い）・意義（1--2段落）

研究目的（問い）を提示する。「本稿では、xxxを明らかにする」「どの程度yyyなのか？」など、何をやるのかが明確になるような具体的な目的や問いを提示する。

また、その問いを明らかにすることがなぜ重要なのか、その意義について述べる。

## 先行研究・理論枠組み・仮説 {#writepaper_theory}

この章では、**序論で述べた背景および研究目的に照らして、必要となる情報をよりくわしくまとめ、分析への橋渡しをする**。便宜的にこれを「第2章」とよぼう。通常、章の下に2--3程度の節を設ける。論文によって分け方は様々なので、これと決まった形式はない。しかし、なんでも書けばよいということではない。ここでは、いくつか既存論文の例を紹介して、どのようにこの章が構成されているのかを見ていこう。

> [Mugiyama, Ryota and kohei Toyonaga. 2021. "Role of Cohort Size in Trends in Class and Occupational Returns to Education at First Job: The Case of Japan." European Sociological Review.](https://doi.org/10.1093/esr/jcab037)
>
> **論文の背景と目的**：高学歴化が進むと学歴（大卒資格）の価値が低下し、大卒であったとしてもよい職業には就けなくなるとされている。しかし、実は高学歴化が進んでもあまりそうした傾向が見られない社会がある。こうした社会では、高学歴化（大卒割合の増加）と並行して少子化（若いコーホートの人数の減少）が進んだために、大卒者が就くことのできるよい職業が足りなくなるといった変化が起こらなかったのではないだろうか？そこで、高学歴化と並行して少子化が進んだ社会である日本のデータを分析して、この仮説を検証する。
>
> この論文の「第2章」は、上記の背景と問いに対応する、次の内容から構成されている。
>
> -   先行研究における学歴と職業の関係に対する説明
> -   なぜ少子化（コホートの人数の減少）が起こると大卒は有利になるのか
> -   日本における高学歴化と少子化のトレンド（および仮説）

> [麦山亮太，2017，「職業経歴と結婚への移行：雇用形態・職種・企業規模と地位変化の効果における男女差」『家族社会学研究』29(2): 129-141．](https://doi.org/10.4234/jjoffamilysociology.29.129)
>
> **論文の背景と目的**：不安定な雇用は日本をはじめ先進諸国における家族形成、とりわけ結婚の遅れの原因と目されており、これは日本でも例外ではない。しかしながら、雇用形態以外の労働市場における地位は結婚への移行とどのように関係しているのか、および、地位が変わることがどのように関係しているのかといった点については十分に明らかになっていない。そこで、雇用形態だけでなく職種・企業規模がどのような効果を持つのか、および、地位の（非）変化がそれぞれ結婚に対してどのような効果を持つのかを明らかにする。
>
> この論文の「第2章」は次の内容から構成されている。
>
> -   地位と結婚への移行の関係を説明する理論
> -   職種と企業規模はなぜ・どのように結婚への移行と関係をもつと考えられるか
> -   地位の（非）変化はなぜ・どのように結婚への移行と関係をもつと考えられるか

上記の論文の例のように、いずれも序論で提示した背景と目的から導かれる疑問点に合わせて、その内容を詳述するかたちで書かれるのが理想である[^12-writepaper-5]。一般的にいって、「第2章」には次のような内容が書かれる傾向がある（すべて書く必要はない）。

[^12-writepaper-5]: もちろんこれは理想であって、実際に実現するのはプロの研究者であっても難しい。

-   先行研究における（現象を説明する）理論
-   先行研究における知見
-   先行研究の問題点
-   先行研究の問題点の克服方法
-   仮説とその根拠

もちろん、すぐにこのような構成を導くのはとても難しいので、はじめはお手本となる論文をみつけて、その構成や書き方をまねたりしてみるのがよい。

## 方法 {#writepaper_method}

方法では、**用いるデータと分析対象、分析に使用した変数、分析手法**を書く。

### データと分析対象

第1段落では、何の調査データを使用するのか、そのデータがいつ、どのような人を対象にして、どのように収集されたのかを書く。また、このデータが研究目的に照らして適切なデータであること、その理由を書く。

第2段落では、上記調査データのうち誰を分析の対象とするのかを書く（例:25--64歳の有業の男女、ひとり親世帯のみ、etc）。可能であれば、もともとの分析対象者の人数と、欠損値（NA）を除いた後の人数とを書く。

### 変数

分析に使用する変数について書く。それぞれ、**変数が何を指していて、どのように定義されたのかを正確に説明する**[^12-writepaper-6]。「他の人が読んだら自分と同じように理解できるか」というのを意識しながら書くとよい。おおむね、このような順番で変数を説明していくことが多い：

[^12-writepaper-6]: ただし、論文の読者にとって自明な変数の場合はわざわざその定義までくわしく説明しないことは多い。たとえば、性別など。年齢については、年齢を連続変数として使う場合もあれば、10歳区切りなどの年齢層に区切って使う場合もあるので、どのように使うかについては説明が必要。学歴も、「最後に**卒業した**学校」なのか「最後に**通った**学校」なのか、また学歴のカテゴリ分けについても研究によって異なっているため、説明が必要。

まず最初に、従属変数について書く。変数の説明については、たとえばたんに「最終学歴を使う」とだけ書くのではなく、どのようなカテゴリに分けたのかといったことまで書く。いくつかの変数を組み合わせて加工する場合（例：年収と労働時間を組み合わせて時間あたり賃金の変数を作成した場合）には、その手続きについても書く。分野において一般的でない変数については、どのような質問項目でそれを尋ねているのかということについても書く。

ついで、独立変数について書く。とくに、最も主眼となる変数を一番はじめに書く。男女で賃金がどの程度異なるのかを分析するという場合であれば性別、ひとり親世帯出身者とふたり親世帯出身者で教育達成がどの程度異なるのかを分析するという場合であれば世帯構成（ひとり親か、ふたり親か）が、ここに書くべき変数ということになる。

その次に、媒介変数や交互作用の検討に使う変数について書く。男女の賃金格差が職業の違いによってどの程度説明できるのかを分析するという論文であれば、職業に関する説明がここに書くべき内容になる。このような変数がない場合には、省略してよい。

最後に、その他の統制変数について書く。

なお変数については見出しをつけて（箇条書きにして）、一つひとつ説明していくというスタイルもあるので、好きな書き方で書くと良い。もちろんその場合であっても、その変数がどのように作成されたのかを丁寧に説明する。

### 分析手法

どのように分析を行うかを書く。

一般的でない分析手法を使う場合には、その手法についての具体的な説明が必要。説明が必要かどうかは、聞く人の理解度によって異なる。この授業では、度数分布、クロス集計、相関係数、平均値の比較、回帰分析くらいであれば、説明は不要。それ以外の手法を使う場合には、説明を書く。

## 結果 {#writepaper_results}

結果では、どのような分析をしたのか、その結果について記述する。**自身の提示した問いに関係するものだけを書き**、そうでないものについては（たとえそれがどんなに興味深い内容であったとしても）書く必要はない。

表や図を使う場合、細かい数字を一つひとつ確認する必要はない。しかし、仮に読者が表や図を見なかったり、あるいはそれを読むことができる知識を持っていなかったとしても、どのような結果なのか本文だけを読めば理解できるような記述が望ましい。まずは、「もしこの授業を取っていない（=統計や社会学を勉強していない）大学の友だちがゼミの課題文献でこのレポートを読んだとしたら、理解できるだろうか？」というのが一つの目安になるだろう。

原則として「結果」の部分では考察や解釈には大きく踏み込まず、結果が表すことの意味については「結論」の部分で論じる。

「第2章」の部分と同じく、結果の構成は比較的自由度が高く、必ずしも以下のように分ける必要はない。ただし、基本的には単純な分析から難しい分析へと展開していくことが多く（たとえば[平均値の比較](#tabulate_summarize)→[重回帰分析](#regression_advanced)）、その逆はほとんどない。

結果については、図表の数を多くしすぎるのは禁物である。やったことを全部書きたいという気持ちになるかもしれないが、図表が多ければ多いほど、一つひとつの図表のメッセージは薄まると考えるとよい。最大20,000字程度の論文であれば、図表の数は全部で4〜7程度が標準的だろう。

### 記述的分析

分析結果について述べる場合、まずはじめに記述的な（2変量の）分析が置かれることが多い。次項で回帰分析など他の要因を統制した分析を行う場合には、それにつながるような分析をするに留める。

### 回帰分析

前項の記述的分析を踏まえて、回帰分析などを行う。

## 結論 {#writepaper_conclusion}

結論は**研究でわかったことをまとめたうえで、考察と議論を展開し、そのインパクトについて論じる**章である。以下のような内容から構成される。

### 背景と目的の再確認（1段落）

1.  研究の背景を再確認する。
2.  先行研究でわかっていなかったこと・不十分な点を再確認する。
3.  研究目的あるいは問いを再確認する。

読者は論文をさかのぼって読まない。なので、改めて「序論」で示した内容を簡潔に確認し、論文で提示した問いに対する答えを述べるための準備をする。

### 分析結果の要約と解釈・議論（2--4段落）

分析の結果を要約する。そのうえで、その結果がどのようなことを意味しているのか、考察や議論を展開する。

事前の仮説を立てたのだとしたら、それが当てはまったか、当てはまらなかったかについて書く。当てはまったとしたら、その仮説を導いたときの根拠に照らしながら、考察や議論を述べる。当てはまらなかったとしたら、なぜ当てはまらなかったのか、その原因について考察する。

また、分析結果を受けて、さらに広い議論を展開するとよい。たとえば、次のようなものが挙げられる。

-   政策的示唆：本研究の分析結果を踏まえれば、論文冒頭で掲げた社会問題を解決するためには、このような政策が有効なのではないか？従来は見落とされてきた、このような層への支援が必要なのではないか？etc.
-   学術的示唆：先行研究は主としてこのような点に焦点を当ててきたが、それでは不十分なのではないか？先行研究が提示してきた説明というのは、必ずしも正しくないのではないか？etc.

もちろん、研究目的から大きく外れた議論を展開してはいけない。あくまで、分析結果（や先行研究）をもとにした自分なりの示唆・考察を述べる。

### 課題・限界（1段落）

本論文に残る課題、限界について書く。ただし、反省文ではなく、今後の研究では、このようなことを分析すると良いのではないかというような方向性を提示する。そうすると、この論文を読んだ他の人が研究を進めやすくなる。

課題や限界は、あまり長く書き過ぎないように[^12-writepaper-7]。できなかったことよりもできたことに目を向けよう。

[^12-writepaper-7]: 個人的には、結論での議論や考察に比べて課題が極端に長いと、せっかく行った研究のアピールポイントが削がれてしまうように感じてしまう。ただし、これについては課題を長々書くのが科学的に誠実な態度だと言う人もいて、好みがあると思う。

### まとめ（1段落、任意）

最後が課題で終わるとなんだか後ろ向きの印象を残してしまう。そこで最後に、「こうした課題はあるけれど、でも本論文はとても重要な貢献をしたんだよ！」ということを書く。

## 謝辞 {#writepaper_acknowledgment}

社会調査データは回答者、調査の企画・実施者を含めたくさんの人の協力があってはじめて成り立っていることを忘れてはいけない。そこで既存社会調査データを二次分析する際には、謝辞の記載が求められる。既存社会調査データを借り出して論文を書いた場合には、**必ずデータを利用した旨の謝辞を書く**。

JGSSの場合は、[こちらのページ](https://jgss.daishodai.ac.jp/data/dat_acknowledgement.html)を参照して謝辞を書く。たとえばJGSS2015を利用した場合には次のような謝辞を書くことになっている：

> 日本版General Social Surveys（JGSS）は、大阪商業大学JGSS研究センター（文部科学大臣認定日本版総合的社会調査共同研究拠点）が、大阪商業大学の支援を得て実施している研究プロジェクトである。JGSS-2015は、JSPS科研費JP26245060、JP15H03485、JP24243057、大阪商業大学アミューズメント産業研究所、日本経済研究センター研究奨励金2014年度（岩井紀子）、労働問題に関する調査研究助成金2015年度（岩井八郎ほか）の支援を受けた。

SSJDA経由でデータを取得した場合は、次のように書く（「2005年SSM日本調査，2005」の例）：

> 二次分析にあたり、東京大学社会科学研究所附属社会調査・データアーカイブ研究センターSSJデータアーカイブから「2005年SSM日本調査，2005」（2015SSM調査管理委員会）の個票データの提供を受けた。

謝辞の記載方法については、データ利用の際の規約などをよく確認すること。

## 参考文献 {#writepaper_reference}

本文中で引用した参考文献を記載する。本文中で引用していないものは、たとえ論文執筆に際して読んだとしても、参考文献には記載しない。

参考文献の記載方法については、基本的に[社会学評論スタイル](https://jss-sociology.org/bulletin/guide/document/)にしたがうこと。ただし、社会学評論スタイルではサブタイトルは------（2倍ダッシュ）で表記しているが、この授業では、：（コロン）で構わない。[『理論と方法』スタイル](http://www.jams-sociology.org/?page_id=50)である。

また英語論文のスタイルは、社会学評論スタイルではなく、[American Sociological Associationスタイル](https://www.asanet.org/sites/default/files/savvy/documents/teaching/pdfs/Quick_Tips_for_ASA_Style.pdf)にしている。これはたんに自分の好みの問題なので、統一的な形式が取られていれば別のものでも構わない。

参考文献リストはアルファベット（ABC）順で記載し、書籍とウェブサイト、日本語と英語といったふうに分けることはしない。

なおすべての文献をアルファベット順で並べるのは日本の社会学分野では標準的だが、分野によっては、日本語の参考文献と英語の参考文献をわけて、日本語の参考文献は50音順で並べ、英語の参考文献はアルファベット順で並べるというスタイルのところもある。たとえば『[日本労働研究雑誌](https://www.jil.go.jp/institute/zassi/toukou/kitei/youryou.html)』などはこのようなスタイルである。

### 書籍の場合の書き方

**著者名，出版年，『書名』出版社．**の形式で書く。著者が複数の場合は、ナカグロ（・）でつなぐ。

岩間暁子，2008，『女性の就業と家族のゆくえ：格差社会のなかの変容』東京大学出版会．

浅野正彦・矢内勇生，2018，『Rによる計量政治学』オーム社．

### 編著書籍中の論文の場合の書き方

**著者名，出版年，「タイトル」編者名編『書名』出版社，ページ数．**の形式で書く。著者が複数の場合は、ナカグロ（・）でつなぐ。

松浦司，2021，「有配偶者の出産意欲の日台比較」寺村絵理子編『日本・台湾の高学歴女性』晃洋書房，54--72．

### 日本語の雑誌論文の場合の書き方

**著者名，出版年，「タイトル」『雑誌名』巻(号): ページ数．**の形式で書く。著者が複数の場合は、ナカグロ（・）でつなぐ。

余田翔平，2012，「子ども期の家族構造と教育達成格差」『家族社会学研究』24(1): 60--71．

永吉希久子，2012，「日本人の排外意識に対する分断労働市場の影響：JGSS-2006の分析から」『社会学評論』19--35．

### 英語の雑誌論文の場合の書き方

**Family name, First name. Year. "Title." *Journal name.* Volume(Issue): page.**の形式で書く。著者が2名の場合はandでつなぎ、3名以上の場合は,..., and xxx というふうに最後のみandとする。

Torche, Florencia. 2011. "Is a College Degree Still the Great Equalizer? Intergenerational Mobility across Levels of Schooling in the United States." *American Journal of Sociology* 117(3):763--807.

Bol, Thijs, Christina Ciocca Eller, Herman G. van de Werfhorst, and Thomas A. DiPrete. 2019. "School-to-Work Linkages, Educational Mismatches, and Labor Market Outcomes." *American Sociological Review* 84(2):275--307.

### 英語の書籍の場合の書き方

Blau, Peter M. and Otis Dudley Duncan. 1967. *The American Occupational Structure*. Free Press.

### 翻訳書の場合の書き方

Watts, Duncan J. 2011. *Everything is Obvious \*Once You Know the Answer: Why Common Sense is Nonsense.* Atlantic Books.（青木創訳，2014，『偶然の科学』早川書房．）

### ウェブサイトの場合の書き方

内閣府，2021，「令和3年版 男女共同参画白書」内閣府男女共同参画局ホームページ．（2021年11月22日閲覧，<https://www.gender.go.jp/about_danjo/whitepaper/r03/zentai/index.html>）

## そのほかの形式上の注意事項 {#writepaper_style}

形式上の注意事項は以下のとおり。なお、以下の形式を全体としてまとめたWordのテンプレートファイルを作成している。[こちら](https://drive.google.com/drive/folders/1-KpewwZ4M-nZl72Q6h1xpDfB1llfhWnZ?usp=sharing)にアップロードしているので、ダウンロードして上書きして使ってよい。

### 推奨するWordの設定

タイトルのフォントサイズは16pt, サブタイトルは14pt, 章タイトルは12pt, 節タイトルは11pt, その他本文は10.5ptを目安とする。

章タイトルや節タイトルのフォントはゴシック体（游ゴシック、ヒラギノ角ゴシックなど）、それ以外は明朝体（游明朝、ヒラギノ明朝など）とする。

本文中のアルファベットや半角数字、表中のフォントはTimes New Romanを推奨する。

余白は上下左右いずれも30mmとし、1行あたりの文字数は40、1ページあたりの行数は35とする。

フッターにはページ数を記載する。ページ数の位置は中央揃えとする。

### 引用の形式

原則としてauthor-date方式とする。つまり、脚注で引用文献などを示すのではなく、該当する記述の後に（筆者 出版年）を付け、末尾に参考文献としてその書誌情報を記載する方式。何らかの書籍、論文、新聞、雑誌、ウェブサイト、等々、何らかの先行研究や資料を引用するときには必ず引用を記載し、自分の主張や記述とは区別する。より細かい記載方法については[「社会学評論スタイルガイド」](https://jss-sociology.org/bulletin/guide/quotation/)におおむね準拠する。

本文中の記載例：

-   近年では男性と女性ともに非正規雇用者は正規雇用者と比べて結婚しにくいことが示されている（佐々木 2012; 麦山 2017）。

-   Blau and Duncan (1967)が提示した地位達成モデルでは...

### 図表の形式

原則として、表と図はそれぞれ別々の通し番号をつける。（図1, 図2..., 表1, 表2...）

表や図には一見してわかりやすいタイトルをつける。表や図の下には、必要に応じて出所や注をつける。

カテゴリや軸はたんにRの変数名ではなく、それが何を表しているかがわかるような名前がついている状態にする。たとえば1, 2, というふうな数値であれば「そう思う」「どちらかといえばそう思う」...などといった値が入っているほうが良いし、クロス表であれば、行と列がそれぞれ何の変数であるのかわかるようにする、といったような具合である。

表はテンプレートに示したようにWord上の表機能を使ってきれいな状態にすることが好まれることが多い。表を作成する場合、罫線はできるだけ少なくし、かつ、横の罫線のみ使う（縦の横線は使わない）というのが一般的。各章で紹介したように、`gtsummary::tbl_summary()`や`gtsummary::tbl_cross()`、`modelsummary::modelsummary()`を使うことである程度きれいな表を出力することができるので、活用するとよい。いろいろな論文を読んで、形式を真似してみよう。

図であれば、文字が小さくなりすぎないようにする。

以上の図表の例は[先に示したテンプレート](https://drive.google.com/drive/folders/1-KpewwZ4M-nZl72Q6h1xpDfB1llfhWnZ?usp=sharing)上に記載している。

### 脚注

本文の流れのうえでは不要であるが、より詳細な情報などを記載したいときには脚注を使用する[^12-writepaper-8]。Wordの脚注機能を使ってつける。

[^12-writepaper-8]: たとえばこんなふうに。
