# 研究発表をする {#presentation}

データ分析をしたり、論文を書いている途中の段階で、現時点での研究成果や進捗状況について研究発表をすることがある。報告の際には、スライド（PowerPointなど）を使って報告する。

スライドを作る際には、次のような形式を参考にするとよい。

## 発表の構成 {#presentation_outline}

発表の構成は大きく分けて

- タイトル
- 序論（背景および問い）
- 方法
- 分析結果
- 結論

のブロックに分けるとよい。

### 全体の構成を考える

スライドを作り始める前に、全体の構成について考えるとよい。

研究発表に使用するスライドのボリュームはどの程度だろうか。スライドの枚数（ページ数）についてよく言われる基準は、**1枚につき1分程度**というものである。なので、15分間の報告であれば約15枚ということになる。

その枚数と時間を考えて、報告のブロックごとに枚数および報告時間を割り振る。たとえば、以下のような割り振りである。

- タイトル：1枚 = 1分
- 序論、先行研究、仮説：6枚 = 6分
- 方法：3枚 = 3分
- 分析結果：3枚 = 3分
- 結論：2枚 = 2分

1枚につき1分程度というのはあくまで最初の段階での目安であり、実際には各スライドに含まれた内容によって異なってくる（たとえばタイトルのスライドで1分間も話すことはあまりないだろう）。したがって上記はあくまで目安であり、スライドに含まれる内容などを考慮して前後することがある。

プレゼンテーションの際のポイントは、聞く側の気持ちになって考えるということである。自分は自分の研究についてよく知っており、色々調べたり分析したりして作業もしているので、ついつい、たくさんのことを盛り込みたくなってしまう。しかし、聞く側は発表者の研究内容についてはあまり知らず、事前知識もないかもしれない。また、15分間も集中して発表を聞くのは大変である。にもかかわらずたくさんのことを話されると、かえって何が主要な論点なのかが伝わらなくなってしまう。

まずはじめにプレゼンの全体構成や割り振りを考えることで、何が必要な情報で、何が発表のポイントなのかを絞ることにつながり、その結果、主要な論点が伝わらないという事態を避けることができる。

### タイトル

1ページ目には**論文のタイトル**と**発表者の名前・所属**を記載する。「研究発表」というタイトルをつけてはいけない。

そのほか、タイトルのスライドに載っていることの多い情報としては以下のようなものがある。

- 日付とイベントの名前、会場の場所（この授業であれば、2024年x月x日 社会学演習中間発表　など）
- 連絡先
- 発表者の所属のロゴ（大学ロゴの使用に際しては所属先の規定を確認すること）
- 謝辞

### 序論

**問題背景**：これから扱うテーマについて導入をする。

**先行研究の整理**：先行研究で何が明らかになっていて、何が明らかになっていないのかを提示する。

**研究目的・問い**：研究目的ないし問いについて述べる。

**仮説**：問いに関連して仮説を立てた場合には、その仮説、および仮説を導くために用いた理論について説明する。

### 方法

**データ**：どのようなデータを使用したのか、その調査データの名前、どのような人や組織などを対象とした調査なのか、いつ実施された調査なのかを記載する。

**分析対象**：上記の調査データから一部の対象者を選択した場合には、どのような対象者を選択したのかを説明する。

**用いる変数**：従属変数とする変数、独立変数とする変数、統制変数とする変数について、それぞれ説明する。

**分析方法（任意）**：聴衆のなかにその分析方法について知らない人が（たとえば、1/3以上）いるかもしれないと考えられる場合には、分析方法について説明する。また、回帰分析のようによく知られている方法であっても、複数のモデルを用いた分析を行う場合には、そのことについて説明するとよいだろう。

### 分析結果

分析した結果を提示する。ただし、やったことを何でもかんでも提示するのではなく、最初に立てた問いに関係するものを主として取り上げるのが原則。

**2変数の分析**：クロス集計表、平均値の比較などといった2変数単位の分析を中心にする。

**回帰分析など**：他の要因を統制したうえでも関連が見られるかどうか、他の変数と組み合わせた場合の結果などについて、回帰分析を行った際の結果を提示する。

### 結論

**分析結果のまとめ**：得られた分析結果を要約する。10分程度の短い報告の場合には省略可能。

**考察・課題**：得られた分析結果の考察や、仮説が支持された（されなかった）としたらそれはなぜかを記載する。また、研究内容に関して現在悩んでいる点、今後の課題を記載する。

## その他気をつけるとよいこと {#presentation_tips}

### 聴衆が誰かを考える

発表を行う際には、聴衆が誰であるかを考えることが重要である。たとえば大学教員であれば、授業で学生に向けて話すときと、研究者の前で研究発表を行うときとでは（仮に同じ内容を話すとしても）どのように説明するかを変えている。

<!----
この箇所を後ほど加筆
---->

### 事前に発表練習をする

一度発表に用いるスライドを作り終えたら、実際に話して発表練習をするとよい。実際に発表練習をしてみることの最大の利点は、発表内容が決められた時間内に収まるかを確認できるということである。

決められた発表時間内に報告を終えることは何より重要である。学会などでは報告者ごとに決められた時間があり、報告時間が伸びると他の報告者の時間を圧迫してしまったり、自身の報告に対してコメントをもらう時間がなくなってしまったりして、望ましくない。また聴衆も、決められた時間を超えた発表は聞く気力がなくなってしまう。発表練習をすることで、時間が長すぎるかどうかを実際に確かめることができるし、どの箇所が不要なのかを見極めることができる。

上記に述べたように、報告のブロックは大きく分けて序論、方法、結果、結論の順にまとまっていることが多い。そのため、たとえば

- 発表時間が10分：序論4分→方法2分→結果3分→結論1分
- 発表時間が15分：序論7分→方法2分→結果5分→結論1分
- 発表時間が20分：序論10分→方法3分→結果6分→結論1分

というように、各ブロックを何分間で終えるかを決めておくとよい。そうすることで、発表中にここのブロックは長すぎると思えば、あとのブロックを省略して発表することができる。

### 文字は大きく少なく

左上から右下まで文字が詰まったスライドはとても見にくい。聴衆の側から見ると、文字を読みながら話を聞くことは難しく、また目の前に文字があるとつい文字を読むことに注意が割かれる。そのため、スライドが文字で埋め尽くされていると、聴衆は発表者の話を聞くことではなく、スライドの文字を目で追うことに集中してしまい、話を聞いてくれなくなる。

また、スライドの文字が小さいと後ろのほうに座っている人からは見えない。

以上の理由から、スライドの文字は可能な限り少なめに、かつ大きくするとよい。

### スライドにはページ数を書く

質疑応答の際に、スライドのページ数に言及することがある。その際にページ数があると便利なので、つけておくとよい。

### スライドつくりの参考資料

[麦山のResearchmap](https://researchmap.jp/mugiyama)にスライドをアップロードしているので、みてみると参考になるかもしれない。

ほかにも、みやすいスライドの作り方を解説した資料はたくさんある。たとえば以下のような書籍や資料を参考にするとよい。

- [伝わるデザイン：研究発表のユニバーサルデザイン](https://tsutawarudesign.com/)：たいへんよくまとまっているウェブサイト。筆者らのアイデアをまとめて、さらに詳しく解説したものとして以下の書籍がある。

- 高橋佑磨・片山なつ，2021，『伝わるデザインの基本 増補改訂3版 良い資料を作るためのレイアウトのルール』 技術評論社．

また、よりやさしく説明した資料として以下がある。「高校生の」とあるが、大学生はもちろん、研究者にとっても大変有益。

- [伝わるデザイン：高校生のための研究発表の手引き](https://student.tsutawarudesign.com/slide_design/)

