project:
  type: book

book:
  title: "Rによる社会調査データ分析の手引き"
  author: "Ryota Mugiyama"
  date: "1/16/2024"
  chapters:
    - index.qmd
    - 01-plan.qmd
    - 02-preparation.qmd
    - 03-import.qmd
    - 04-handling.qmd
    - 05-descriptives.qmd
    - 06-tabulate.qmd
    - 07-regression_basic.qmd
    - 08-regression_advanced.qmd
    - 09-interaction.qmd
    - 10-logit.qmd
    - 11-domain.qmd
    - 12-writepaper.qmd
    - 13-presentation.qmd
    - 14-reference.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



