--- 
title: "Rによる社会調査データ分析の手引き"
author: "麦山 亮太（学習院大学法学部政治学科）/ Ryota Mugiyama (Department of Political Studies, Gakushuin University)"
date: "Last update: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the document for the class *Seminar in Sociology* held in Department of Political Studies, Gakushuin University. Anyone can freely use this as reference."
---

# まえがき {-}

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

knitr::opts_chunk$set(warning = FALSE, error = FALSE)
```

本資料は麦山が担当する学習院大学法学部政治学科「社会学演習（社会的不平等に関する実証研究）」、同大学院政治学研究科「統計解析I」「公共秩序の数理モデル（社会調査データの計量分析）」の授業で使用する資料です。その他の授業でも活用することがあります。授業では適宜口頭で説明を補いながら使うことを想定しているため説明を簡単に済ませているところもありますが、どなたでも参照できるかと思います。分かりやすさを重視しているため、厳密性には欠けるところがあるかもしれません。

タイトルに示されているとおり、本資料の目的はとくに社会調査の個票データを分析するうえで必要となるR/RStudioの使い方、そしてその前後に研究計画の立て方と論文のまとめかたを置き、一通り社会調査データの分析のための作法を整理して記したものです。扱っている内容は左記の目次のとおりです。スマートフォンで見ている場合には上部にある4本線のアイコンをクリックすることで目次をみることができます。

本資料は、麦山の専門分野である社会学、とりわけ社会階層研究を念頭に置き、かつ既存の社会調査データを利用することを念頭において作成しています。そのため、分野が異なる、扱うデータの形式が異なるといった場合には適宜距離を取って参照してください。

（発展）と書いてある節または項は発展的な内容を扱っているため、必ずしもチェックする必要はありませんが、読んでおくと勉強になるかもしれません。

本資料は（いつまでも）ベータ版で、今後授業などを通じて少しずつアップデートしていく予定です。アップデートは予告なしに行います。もし本資料をご利用いただいた方で、誤り、改善点、要望、感想、その他もっとこうしたほうがよいといった点などについてコメントいただける方は、[こちらのフォーム](https://docs.google.com/forms/d/e/1FAIpQLSdjnZdFZjAWT6CfmUIPGWOTOJ3qrsm7WzGgj4qDEnYC9Wni2Q/viewform?usp=sf_link)からコメントをお寄せください。主として自分の授業のための資料ですので、すべての要望に答えることはできませんが、改善のための参考にさせていただきます。フォームから質問をもらっても回答はできません。

今後追加するかもしれないトピック（2022/5/30追記）
- 最小二乗法の説明
- 交互作用
- ロジスティック回帰分析