---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# 統計的推測・統計的仮説検定 {#inference}

```{r}
library(tidyverse)
library(gtsummary)
library(flextable)
library(modelsummary)
library(broom)
```

## 中心極限定理

```{r}
set.seed(123)
samplesize = 10

x <- rnorm(mean = 50, sd = 10, n = samplesize * 1000)
sample <- rep(1:1000, samplesize)
df <- tibble(x, sample) %>% 
  arrange(sample)

df %>%
  group_by(sample) %>% 
  summarize(mean_x = mean(x)) %>% 
  ggplot(aes(x = mean_x)) + 
  geom_histogram() + 
  xlim(40, 60)

df %>% 
  group_by(sample) %>% 
  summarize(mean_x = mean(x)) %>% 
  ungroup() %>% 
  summarize(sd_mean_x = sd(mean_x)) %>% 
  mutate(se_mean_x = sd_mean_x / sqrt(10))
```


```{r}
set.seed(123)
samplesize = 100

x <- rnorm(mean = 50, sd = 10, n = samplesize * 1000)
sample <- rep(1:1000, samplesize)
df <- tibble(x, sample) %>% 
  arrange(sample)

df %>%
  group_by(sample) %>% 
  summarize(mean_x = mean(x)) %>% 
  ggplot(aes(x = mean_x)) + 
  geom_histogram() + 
  xlim(40, 60)

```

## 区間推定と信頼度

## 母平均・母比率（1変数の要約統計量）の区間推定

### 母平均の区間推定

### 母比率の区間推定

## 統計的仮説検定とは何か



## 平均値・比率の差の検定

### 平均値の差の検定

### 比率の差の検定

## 回帰分析の係数の検定

### 1つの係数の検定：t検定

### 複数の係数の同時検定：F検定